target 'Skugga-iOS' do
  use_frameworks!
  platform :ios, '10.0'
  workspace 'Skugga'
  project 'iOS/Skugga-iOS.xcodeproj'

  pod 'SDWebImage', '~> 3.7.1'
  pod 'DateToolsSwift'
end

target 'Skugga-macOS' do
  use_frameworks!
  platform :osx, '10.11'
  workspace 'Skugga'
  project 'macOS/Skugga-macOS.xcodeproj'

  pod 'OTWebImage', :git => 'https://github.com/OpenFibers/OTWebImage.git'
  pod 'DateToolsSwift'
end
