# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Share-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Share

end

target 'Skugga-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Skugga
	pod 'AFNetworking', '~> 2.5'
	pod 'SDWebImage', '~> 3.7.1'
	pod 'DateToolsSwift'
end
